### ISSUE TITLE
[Feature-Request]: Absolute path/ Alias Folders

### ISSUE THREAD

**Issue by sperezm97** [jsmr04/react-native-my-template#2]
As a developer, i want to be able to set up my default folders by alias path so that the Intelysis can autocomplete faster, which certainly increases the DE for the template. 

### Technical Information 

[react-native-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) aka babel
[Path alias in TS](https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353)

**Comment by jsmr04** [comment]
Examples:
import OneLine from '~components/atoms/OneLine' instead of import OneLine from '../../components/atoms/OneLine'
import OneLine from '~screens/Login' instead of import OneLine from '../../../screens/Login'
